name: Verify pull request code quality
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install python pip
      - run: ./tools/restore.sh
      - run: ./tools/test.sh
